// ==============================================
// DAWA.ma Database Types
// Auto-generated from Supabase schema
// Run: pnpm db:generate-types to regenerate
// ==============================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      patients: {
        Row: {
          id: string;
          phone: string;
          phone_verified: boolean;
          email: string | null;
          email_verified: boolean;
          first_name_encrypted: string;
          last_name_encrypted: string;
          date_of_birth_encrypted: string | null;
          gender: string | null;
          national_id_encrypted: string | null;
          default_address_id: string | null;
          insurance_provider_id: string | null;
          insurance_member_id_encrypted: string | null;
          ramed_beneficiary: boolean;
          language: string;
          notification_preferences: Json;
          consent_data_processing: boolean;
          consent_data_processing_date: string | null;
          consent_marketing: boolean;
          consent_marketing_date: string | null;
          consent_version: string | null;
          status: string;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          phone: string;
          phone_verified?: boolean;
          email?: string | null;
          email_verified?: boolean;
          first_name_encrypted: string;
          last_name_encrypted: string;
          date_of_birth_encrypted?: string | null;
          gender?: string | null;
          national_id_encrypted?: string | null;
          default_address_id?: string | null;
          insurance_provider_id?: string | null;
          insurance_member_id_encrypted?: string | null;
          ramed_beneficiary?: boolean;
          language?: string;
          notification_preferences?: Json;
          consent_data_processing?: boolean;
          consent_data_processing_date?: string | null;
          consent_marketing?: boolean;
          consent_marketing_date?: string | null;
          consent_version?: string | null;
          status?: string;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          phone?: string;
          phone_verified?: boolean;
          email?: string | null;
          email_verified?: boolean;
          first_name_encrypted?: string;
          last_name_encrypted?: string;
          date_of_birth_encrypted?: string | null;
          gender?: string | null;
          national_id_encrypted?: string | null;
          default_address_id?: string | null;
          insurance_provider_id?: string | null;
          insurance_member_id_encrypted?: string | null;
          ramed_beneficiary?: boolean;
          language?: string;
          notification_preferences?: Json;
          consent_data_processing?: boolean;
          consent_data_processing_date?: string | null;
          consent_marketing?: boolean;
          consent_marketing_date?: string | null;
          consent_version?: string | null;
          status?: string;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'patients_default_address_id_fkey';
            columns: ['default_address_id'];
            referencedRelation: 'addresses';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'patients_insurance_provider_id_fkey';
            columns: ['insurance_provider_id'];
            referencedRelation: 'insurance_providers';
            referencedColumns: ['id'];
          }
        ];
      };
      pharmacies: {
        Row: {
          id: string;
          name: string;
          license_number: string;
          license_verified: boolean;
          license_expiry_date: string | null;
          owner_pharmacist_id: string | null;
          address_line_1: string;
          address_line_2: string | null;
          city: string;
          region: string;
          postal_code: string | null;
          location: unknown | null;
          phone_primary: string;
          phone_secondary: string | null;
          email: string | null;
          whatsapp: string | null;
          operating_hours: Json;
          is_24_hour: boolean;
          is_pharmacie_de_garde: boolean;
          garde_schedule: Json | null;
          accepts_prescriptions: boolean;
          accepts_otc: boolean;
          accepts_cosmetics: boolean;
          has_cold_storage: boolean;
          delivery_radius_km: number;
          average_preparation_time_minutes: number;
          commission_rate: number;
          bank_account_encrypted: string | null;
          tax_id_encrypted: string | null;
          rating_average: number;
          rating_count: number;
          order_count: number;
          fulfillment_rate: number;
          status: string;
          onboarding_completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          license_number: string;
          license_verified?: boolean;
          license_expiry_date?: string | null;
          owner_pharmacist_id?: string | null;
          address_line_1: string;
          address_line_2?: string | null;
          city: string;
          region: string;
          postal_code?: string | null;
          location?: unknown | null;
          phone_primary: string;
          phone_secondary?: string | null;
          email?: string | null;
          whatsapp?: string | null;
          operating_hours: Json;
          is_24_hour?: boolean;
          is_pharmacie_de_garde?: boolean;
          garde_schedule?: Json | null;
          accepts_prescriptions?: boolean;
          accepts_otc?: boolean;
          accepts_cosmetics?: boolean;
          has_cold_storage?: boolean;
          delivery_radius_km?: number;
          average_preparation_time_minutes?: number;
          commission_rate?: number;
          bank_account_encrypted?: string | null;
          tax_id_encrypted?: string | null;
          rating_average?: number;
          rating_count?: number;
          order_count?: number;
          fulfillment_rate?: number;
          status?: string;
          onboarding_completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          license_number?: string;
          license_verified?: boolean;
          license_expiry_date?: string | null;
          owner_pharmacist_id?: string | null;
          address_line_1?: string;
          address_line_2?: string | null;
          city?: string;
          region?: string;
          postal_code?: string | null;
          location?: unknown | null;
          phone_primary?: string;
          phone_secondary?: string | null;
          email?: string | null;
          whatsapp?: string | null;
          operating_hours?: Json;
          is_24_hour?: boolean;
          is_pharmacie_de_garde?: boolean;
          garde_schedule?: Json | null;
          accepts_prescriptions?: boolean;
          accepts_otc?: boolean;
          accepts_cosmetics?: boolean;
          has_cold_storage?: boolean;
          delivery_radius_km?: number;
          average_preparation_time_minutes?: number;
          commission_rate?: number;
          bank_account_encrypted?: string | null;
          tax_id_encrypted?: string | null;
          rating_average?: number;
          rating_count?: number;
          order_count?: number;
          fulfillment_rate?: number;
          status?: string;
          onboarding_completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      orders: {
        Row: {
          id: string;
          order_number: string;
          patient_id: string;
          prescription_id: string | null;
          pharmacy_id: string | null;
          courier_id: string | null;
          order_type: string;
          delivery_address_id: string;
          delivery_location: unknown | null;
          is_scheduled: boolean;
          scheduled_date: string | null;
          scheduled_time_slot: string | null;
          status: string;
          status_history: Json;
          pharmacy_accepted_at: string | null;
          pharmacist_reviewed_at: string | null;
          preparation_started_at: string | null;
          ready_for_pickup_at: string | null;
          courier_assigned_at: string | null;
          picked_up_at: string | null;
          delivered_at: string | null;
          delivery_verification_type: string | null;
          delivery_otp_hash: string | null;
          delivery_signature_url: string | null;
          delivery_photo_url: string | null;
          recipient_name: string | null;
          subtotal: number;
          delivery_fee: number;
          service_fee: number;
          discount_amount: number;
          discount_code: string | null;
          total_amount: number;
          insurance_claim_id: string | null;
          insurance_covered_amount: number;
          patient_copay_amount: number | null;
          payment_method: string | null;
          payment_status: string;
          payment_transaction_id: string | null;
          paid_at: string | null;
          patient_notes: string | null;
          pharmacy_notes: string | null;
          courier_notes: string | null;
          cancelled_by: string | null;
          cancellation_reason: string | null;
          cancelled_at: string | null;
          patient_rating_pharmacy: number | null;
          patient_rating_courier: number | null;
          patient_rating_comment: string | null;
          rated_at: string | null;
          estimated_preparation_minutes: number | null;
          actual_preparation_minutes: number | null;
          estimated_delivery_minutes: number | null;
          actual_delivery_minutes: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_number?: string;
          patient_id: string;
          prescription_id?: string | null;
          pharmacy_id?: string | null;
          courier_id?: string | null;
          order_type: string;
          delivery_address_id: string;
          delivery_location?: unknown | null;
          is_scheduled?: boolean;
          scheduled_date?: string | null;
          scheduled_time_slot?: string | null;
          status?: string;
          status_history?: Json;
          pharmacy_accepted_at?: string | null;
          pharmacist_reviewed_at?: string | null;
          preparation_started_at?: string | null;
          ready_for_pickup_at?: string | null;
          courier_assigned_at?: string | null;
          picked_up_at?: string | null;
          delivered_at?: string | null;
          delivery_verification_type?: string | null;
          delivery_otp_hash?: string | null;
          delivery_signature_url?: string | null;
          delivery_photo_url?: string | null;
          recipient_name?: string | null;
          subtotal?: number;
          delivery_fee?: number;
          service_fee?: number;
          discount_amount?: number;
          discount_code?: string | null;
          total_amount?: number;
          insurance_claim_id?: string | null;
          insurance_covered_amount?: number;
          patient_copay_amount?: number | null;
          payment_method?: string | null;
          payment_status?: string;
          payment_transaction_id?: string | null;
          paid_at?: string | null;
          patient_notes?: string | null;
          pharmacy_notes?: string | null;
          courier_notes?: string | null;
          cancelled_by?: string | null;
          cancellation_reason?: string | null;
          cancelled_at?: string | null;
          patient_rating_pharmacy?: number | null;
          patient_rating_courier?: number | null;
          patient_rating_comment?: string | null;
          rated_at?: string | null;
          estimated_preparation_minutes?: number | null;
          actual_preparation_minutes?: number | null;
          estimated_delivery_minutes?: number | null;
          actual_delivery_minutes?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_number?: string;
          patient_id?: string;
          prescription_id?: string | null;
          pharmacy_id?: string | null;
          courier_id?: string | null;
          order_type?: string;
          delivery_address_id?: string;
          delivery_location?: unknown | null;
          is_scheduled?: boolean;
          scheduled_date?: string | null;
          scheduled_time_slot?: string | null;
          status?: string;
          status_history?: Json;
          pharmacy_accepted_at?: string | null;
          pharmacist_reviewed_at?: string | null;
          preparation_started_at?: string | null;
          ready_for_pickup_at?: string | null;
          courier_assigned_at?: string | null;
          picked_up_at?: string | null;
          delivered_at?: string | null;
          delivery_verification_type?: string | null;
          delivery_otp_hash?: string | null;
          delivery_signature_url?: string | null;
          delivery_photo_url?: string | null;
          recipient_name?: string | null;
          subtotal?: number;
          delivery_fee?: number;
          service_fee?: number;
          discount_amount?: number;
          discount_code?: string | null;
          total_amount?: number;
          insurance_claim_id?: string | null;
          insurance_covered_amount?: number;
          patient_copay_amount?: number | null;
          payment_method?: string | null;
          payment_status?: string;
          payment_transaction_id?: string | null;
          paid_at?: string | null;
          patient_notes?: string | null;
          pharmacy_notes?: string | null;
          courier_notes?: string | null;
          cancelled_by?: string | null;
          cancellation_reason?: string | null;
          cancelled_at?: string | null;
          patient_rating_pharmacy?: number | null;
          patient_rating_courier?: number | null;
          patient_rating_comment?: string | null;
          rated_at?: string | null;
          estimated_preparation_minutes?: number | null;
          actual_preparation_minutes?: number | null;
          estimated_delivery_minutes?: number | null;
          actual_delivery_minutes?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      prescriptions: {
        Row: {
          id: string;
          patient_id: string;
          image_url_encrypted: string;
          image_hash: string;
          upload_type: string;
          doctor_name: string | null;
          doctor_license_number: string | null;
          clinic_hospital: string | null;
          prescription_date: string | null;
          verification_status: string;
          verified_by_pharmacist_id: string | null;
          verified_at: string | null;
          verification_notes: string | null;
          rejection_reason: string | null;
          contains_controlled_substance: boolean;
          requires_special_handling: boolean;
          is_chronic_refill: boolean;
          parent_prescription_id: string | null;
          valid_until: string | null;
          refills_remaining: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          patient_id: string;
          image_url_encrypted: string;
          image_hash: string;
          upload_type: string;
          doctor_name?: string | null;
          doctor_license_number?: string | null;
          clinic_hospital?: string | null;
          prescription_date?: string | null;
          verification_status?: string;
          verified_by_pharmacist_id?: string | null;
          verified_at?: string | null;
          verification_notes?: string | null;
          rejection_reason?: string | null;
          contains_controlled_substance?: boolean;
          requires_special_handling?: boolean;
          is_chronic_refill?: boolean;
          parent_prescription_id?: string | null;
          valid_until?: string | null;
          refills_remaining?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          patient_id?: string;
          image_url_encrypted?: string;
          image_hash?: string;
          upload_type?: string;
          doctor_name?: string | null;
          doctor_license_number?: string | null;
          clinic_hospital?: string | null;
          prescription_date?: string | null;
          verification_status?: string;
          verified_by_pharmacist_id?: string | null;
          verified_at?: string | null;
          verification_notes?: string | null;
          rejection_reason?: string | null;
          contains_controlled_substance?: boolean;
          requires_special_handling?: boolean;
          is_chronic_refill?: boolean;
          parent_prescription_id?: string | null;
          valid_until?: string | null;
          refills_remaining?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      addresses: {
        Row: {
          id: string;
          patient_id: string | null;
          label: string | null;
          address_line_1_encrypted: string;
          address_line_2_encrypted: string | null;
          city: string;
          region: string;
          postal_code: string | null;
          location: unknown | null;
          delivery_instructions: string | null;
          is_default: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          patient_id?: string | null;
          label?: string | null;
          address_line_1_encrypted: string;
          address_line_2_encrypted?: string | null;
          city: string;
          region: string;
          postal_code?: string | null;
          location?: unknown | null;
          delivery_instructions?: string | null;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          patient_id?: string | null;
          label?: string | null;
          address_line_1_encrypted?: string;
          address_line_2_encrypted?: string | null;
          city?: string;
          region?: string;
          postal_code?: string | null;
          location?: unknown | null;
          delivery_instructions?: string | null;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      couriers: {
        Row: {
          id: string;
          first_name_encrypted: string;
          last_name_encrypted: string;
          phone: string;
          email: string | null;
          national_id_encrypted: string;
          date_of_birth: string;
          photo_url: string | null;
          employment_type: string;
          cnss_number_encrypted: string | null;
          contractor_registration_encrypted: string | null;
          vehicle_type: string;
          vehicle_registration_encrypted: string | null;
          vehicle_insurance_expiry: string | null;
          medical_courier_training_completed: boolean;
          training_completion_date: string | null;
          training_certificate_url: string | null;
          first_aid_certified: boolean;
          service_areas: Json | null;
          current_location: unknown | null;
          location_updated_at: string | null;
          is_online: boolean;
          current_order_id: string | null;
          rating_average: number;
          rating_count: number;
          delivery_count: number;
          on_time_rate: number;
          earnings_balance: number;
          bank_account_encrypted: string | null;
          status: string;
          background_check_status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          first_name_encrypted: string;
          last_name_encrypted: string;
          phone: string;
          email?: string | null;
          national_id_encrypted: string;
          date_of_birth: string;
          photo_url?: string | null;
          employment_type: string;
          cnss_number_encrypted?: string | null;
          contractor_registration_encrypted?: string | null;
          vehicle_type: string;
          vehicle_registration_encrypted?: string | null;
          vehicle_insurance_expiry?: string | null;
          medical_courier_training_completed?: boolean;
          training_completion_date?: string | null;
          training_certificate_url?: string | null;
          first_aid_certified?: boolean;
          service_areas?: Json | null;
          current_location?: unknown | null;
          location_updated_at?: string | null;
          is_online?: boolean;
          current_order_id?: string | null;
          rating_average?: number;
          rating_count?: number;
          delivery_count?: number;
          on_time_rate?: number;
          earnings_balance?: number;
          bank_account_encrypted?: string | null;
          status?: string;
          background_check_status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          first_name_encrypted?: string;
          last_name_encrypted?: string;
          phone?: string;
          email?: string | null;
          national_id_encrypted?: string;
          date_of_birth?: string;
          photo_url?: string | null;
          employment_type?: string;
          cnss_number_encrypted?: string | null;
          contractor_registration_encrypted?: string | null;
          vehicle_type?: string;
          vehicle_registration_encrypted?: string | null;
          vehicle_insurance_expiry?: string | null;
          medical_courier_training_completed?: boolean;
          training_completion_date?: string | null;
          training_certificate_url?: string | null;
          first_aid_certified?: boolean;
          service_areas?: Json | null;
          current_location?: unknown | null;
          location_updated_at?: string | null;
          is_online?: boolean;
          current_order_id?: string | null;
          rating_average?: number;
          rating_count?: number;
          delivery_count?: number;
          on_time_rate?: number;
          earnings_balance?: number;
          bank_account_encrypted?: string | null;
          status?: string;
          background_check_status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      medications: {
        Row: {
          id: string;
          national_code: string | null;
          barcode: string | null;
          brand_name: string;
          brand_name_arabic: string | null;
          generic_name: string | null;
          generic_name_arabic: string | null;
          atc_code: string | null;
          therapeutic_class: string | null;
          form: string;
          strength: string | null;
          unit: string | null;
          manufacturer: string | null;
          country_of_origin: string | null;
          prescription_required: boolean;
          is_controlled_substance: boolean;
          controlled_substance_schedule: string | null;
          is_cold_chain: boolean;
          storage_requirements: string | null;
          reference_price: number | null;
          status: string;
          search_keywords: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          national_code?: string | null;
          barcode?: string | null;
          brand_name: string;
          brand_name_arabic?: string | null;
          generic_name?: string | null;
          generic_name_arabic?: string | null;
          atc_code?: string | null;
          therapeutic_class?: string | null;
          form: string;
          strength?: string | null;
          unit?: string | null;
          manufacturer?: string | null;
          country_of_origin?: string | null;
          prescription_required?: boolean;
          is_controlled_substance?: boolean;
          controlled_substance_schedule?: string | null;
          is_cold_chain?: boolean;
          storage_requirements?: string | null;
          reference_price?: number | null;
          status?: string;
          search_keywords?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          national_code?: string | null;
          barcode?: string | null;
          brand_name?: string;
          brand_name_arabic?: string | null;
          generic_name?: string | null;
          generic_name_arabic?: string | null;
          atc_code?: string | null;
          therapeutic_class?: string | null;
          form?: string;
          strength?: string | null;
          unit?: string | null;
          manufacturer?: string | null;
          country_of_origin?: string | null;
          prescription_required?: boolean;
          is_controlled_substance?: boolean;
          controlled_substance_schedule?: string | null;
          is_cold_chain?: boolean;
          storage_requirements?: string | null;
          reference_price?: number | null;
          status?: string;
          search_keywords?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      audit_logs: {
        Row: {
          id: string;
          user_type: string;
          user_id: string | null;
          ip_address: string | null;
          user_agent: string | null;
          action: string;
          resource_type: string;
          resource_id: string | null;
          old_values: Json | null;
          new_values: Json | null;
          success: boolean;
          error_message: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_type: string;
          user_id?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          action: string;
          resource_type: string;
          resource_id?: string | null;
          old_values?: Json | null;
          new_values?: Json | null;
          success?: boolean;
          error_message?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_type?: string;
          user_id?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          action?: string;
          resource_type?: string;
          resource_id?: string | null;
          old_values?: Json | null;
          new_values?: Json | null;
          success?: boolean;
          error_message?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {};
    Functions: {
      generate_order_number: {
        Args: Record<PropertyKey, never>;
        Returns: string;
      };
    };
    Enums: {};
    CompositeTypes: {};
  };
}

// Helper types for easier usage
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];

export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];

export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];
