// ==============================================
// DAWA.ma V10 Database Types
// Generated from consolidated schema
// ==============================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      patients: {
        Row: {
          id: string;
          user_id: string | null;
          phone: string;
          phone_verified: boolean;
          email: string | null;
          email_verified: boolean;
          first_name: string;
          last_name: string;
          date_of_birth: string | null;
          gender: 'male' | 'female' | 'other' | null;
          national_id_encrypted: string | null;
          default_address_id: string | null;
          primary_insurance_id: string | null;
          insurance_member_id: string | null;
          is_chronic_patient: boolean;
          chronic_conditions: string[];
          allergies: string[];
          preferred_language: 'ar' | 'fr' | 'en';
          notification_preferences: Json;
          status: 'active' | 'suspended' | 'deleted';
          created_at: string;
          updated_at: string;
          last_active_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          phone: string;
          phone_verified?: boolean;
          email?: string | null;
          email_verified?: boolean;
          first_name: string;
          last_name: string;
          date_of_birth?: string | null;
          gender?: 'male' | 'female' | 'other' | null;
          national_id_encrypted?: string | null;
          default_address_id?: string | null;
          primary_insurance_id?: string | null;
          insurance_member_id?: string | null;
          is_chronic_patient?: boolean;
          chronic_conditions?: string[];
          allergies?: string[];
          preferred_language?: 'ar' | 'fr' | 'en';
          notification_preferences?: Json;
          status?: 'active' | 'suspended' | 'deleted';
          created_at?: string;
          updated_at?: string;
          last_active_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          phone?: string;
          phone_verified?: boolean;
          email?: string | null;
          email_verified?: boolean;
          first_name?: string;
          last_name?: string;
          date_of_birth?: string | null;
          gender?: 'male' | 'female' | 'other' | null;
          national_id_encrypted?: string | null;
          default_address_id?: string | null;
          primary_insurance_id?: string | null;
          insurance_member_id?: string | null;
          is_chronic_patient?: boolean;
          chronic_conditions?: string[];
          allergies?: string[];
          preferred_language?: 'ar' | 'fr' | 'en';
          notification_preferences?: Json;
          status?: 'active' | 'suspended' | 'deleted';
          created_at?: string;
          updated_at?: string;
          last_active_at?: string;
        };
        Relationships: [];
      };
      patient_addresses: {
        Row: {
          id: string;
          patient_id: string;
          label: string;
          street_address: string;
          apartment: string | null;
          city: string;
          postal_code: string | null;
          region: string | null;
          coordinates: unknown | null;
          google_place_id: string | null;
          delivery_instructions: string | null;
          building_access_code: string | null;
          is_default: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          patient_id: string;
          label?: string;
          street_address: string;
          apartment?: string | null;
          city: string;
          postal_code?: string | null;
          region?: string | null;
          coordinates?: unknown | null;
          google_place_id?: string | null;
          delivery_instructions?: string | null;
          building_access_code?: string | null;
          is_default?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          patient_id?: string;
          label?: string;
          street_address?: string;
          apartment?: string | null;
          city?: string;
          postal_code?: string | null;
          region?: string | null;
          coordinates?: unknown | null;
          google_place_id?: string | null;
          delivery_instructions?: string | null;
          building_access_code?: string | null;
          is_default?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'patient_addresses_patient_id_fkey';
            columns: ['patient_id'];
            referencedRelation: 'patients';
            referencedColumns: ['id'];
          }
        ];
      };
      pharmacies: {
        Row: {
          id: string;
          license_number: string;
          tax_id: string | null;
          ice_number: string | null;
          name: string;
          legal_name: string;
          owner_pharmacist_id: string | null;
          phone: string;
          phone_secondary: string | null;
          email: string | null;
          website: string | null;
          street_address: string;
          city: string;
          postal_code: string | null;
          region: string;
          coordinates: unknown;
          google_place_id: string | null;
          delivery_radius_km: number;
          delivery_zones: Json;
          operating_hours: Json;
          is_on_duty: boolean;
          accepts_insurance: boolean;
          accepted_insurers: string[];
          has_drive_through: boolean;
          has_parking: boolean;
          wheelchair_accessible: boolean;
          is_active: boolean;
          accepts_orders: boolean;
          max_daily_orders: number;
          min_order_amount: number;
          delivery_fee: number;
          free_delivery_threshold: number | null;
          tier: 'premium' | 'standard' | 'probation' | 'suspended';
          tier_updated_at: string | null;
          rating_average: number;
          rating_count: number;
          order_count: number;
          created_at: string;
          updated_at: string;
          onboarded_at: string | null;
        };
        Insert: {
          id?: string;
          license_number: string;
          tax_id?: string | null;
          ice_number?: string | null;
          name: string;
          legal_name: string;
          owner_pharmacist_id?: string | null;
          phone: string;
          phone_secondary?: string | null;
          email?: string | null;
          website?: string | null;
          street_address: string;
          city: string;
          postal_code?: string | null;
          region: string;
          coordinates: unknown;
          google_place_id?: string | null;
          delivery_radius_km?: number;
          delivery_zones?: Json;
          operating_hours?: Json;
          is_on_duty?: boolean;
          accepts_insurance?: boolean;
          accepted_insurers?: string[];
          has_drive_through?: boolean;
          has_parking?: boolean;
          wheelchair_accessible?: boolean;
          is_active?: boolean;
          accepts_orders?: boolean;
          max_daily_orders?: number;
          min_order_amount?: number;
          delivery_fee?: number;
          free_delivery_threshold?: number | null;
          tier?: 'premium' | 'standard' | 'probation' | 'suspended';
          tier_updated_at?: string | null;
          rating_average?: number;
          rating_count?: number;
          order_count?: number;
          created_at?: string;
          updated_at?: string;
          onboarded_at?: string | null;
        };
        Update: {
          id?: string;
          license_number?: string;
          tax_id?: string | null;
          ice_number?: string | null;
          name?: string;
          legal_name?: string;
          owner_pharmacist_id?: string | null;
          phone?: string;
          phone_secondary?: string | null;
          email?: string | null;
          website?: string | null;
          street_address?: string;
          city?: string;
          postal_code?: string | null;
          region?: string;
          coordinates?: unknown;
          google_place_id?: string | null;
          delivery_radius_km?: number;
          delivery_zones?: Json;
          operating_hours?: Json;
          is_on_duty?: boolean;
          accepts_insurance?: boolean;
          accepted_insurers?: string[];
          has_drive_through?: boolean;
          has_parking?: boolean;
          wheelchair_accessible?: boolean;
          is_active?: boolean;
          accepts_orders?: boolean;
          max_daily_orders?: number;
          min_order_amount?: number;
          delivery_fee?: number;
          free_delivery_threshold?: number | null;
          tier?: 'premium' | 'standard' | 'probation' | 'suspended';
          tier_updated_at?: string | null;
          rating_average?: number;
          rating_count?: number;
          order_count?: number;
          created_at?: string;
          updated_at?: string;
          onboarded_at?: string | null;
        };
        Relationships: [];
      };
      pharmacy_staff: {
        Row: {
          id: string;
          user_id: string | null;
          pharmacy_id: string;
          first_name: string;
          last_name: string;
          phone: string;
          email: string | null;
          role: 'owner' | 'pharmacist' | 'assistant' | 'technician' | 'admin';
          license_number: string | null;
          license_verified: boolean;
          permissions: Json;
          schedule: Json;
          is_active: boolean;
          verifications_count: number;
          avg_verification_time_seconds: number | null;
          accuracy_score: number | null;
          created_at: string;
          updated_at: string;
          last_active_at: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          pharmacy_id: string;
          first_name: string;
          last_name: string;
          phone: string;
          email?: string | null;
          role: 'owner' | 'pharmacist' | 'assistant' | 'technician' | 'admin';
          license_number?: string | null;
          license_verified?: boolean;
          permissions?: Json;
          schedule?: Json;
          is_active?: boolean;
          verifications_count?: number;
          avg_verification_time_seconds?: number | null;
          accuracy_score?: number | null;
          created_at?: string;
          updated_at?: string;
          last_active_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          pharmacy_id?: string;
          first_name?: string;
          last_name?: string;
          phone?: string;
          email?: string | null;
          role?: 'owner' | 'pharmacist' | 'assistant' | 'technician' | 'admin';
          license_number?: string | null;
          license_verified?: boolean;
          permissions?: Json;
          schedule?: Json;
          is_active?: boolean;
          verifications_count?: number;
          avg_verification_time_seconds?: number | null;
          accuracy_score?: number | null;
          created_at?: string;
          updated_at?: string;
          last_active_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'pharmacy_staff_pharmacy_id_fkey';
            columns: ['pharmacy_id'];
            referencedRelation: 'pharmacies';
            referencedColumns: ['id'];
          }
        ];
      };
      couriers: {
        Row: {
          id: string;
          user_id: string | null;
          first_name: string;
          last_name: string;
          phone: string;
          email: string | null;
          date_of_birth: string;
          national_id_encrypted: string;
          profile_photo_url: string | null;
          vehicle_type: 'motorcycle' | 'bicycle' | 'car' | 'scooter';
          vehicle_plate: string | null;
          vehicle_model: string | null;
          vehicle_year: number | null;
          driver_license_number: string | null;
          driver_license_expiry: string | null;
          insurance_policy_number: string | null;
          insurance_expiry: string | null;
          primary_zone_id: string | null;
          secondary_zones: string[];
          max_delivery_radius_km: number;
          status: 'online' | 'busy' | 'offline' | 'suspended';
          current_location: unknown | null;
          location_updated_at: string | null;
          current_delivery_id: string | null;
          max_concurrent_orders: number;
          current_order_count: number;
          total_deliveries: number;
          successful_deliveries: number;
          average_rating: number;
          total_ratings: number;
          on_time_rate: number;
          acceptance_rate: number;
          earnings_balance: number;
          total_earnings: number;
          last_payout_at: string | null;
          background_check_status: 'pending' | 'passed' | 'failed';
          is_verified: boolean;
          verified_at: string | null;
          is_active: boolean;
          suspended_reason: string | null;
          suspended_until: string | null;
          created_at: string;
          updated_at: string;
          last_active_at: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          first_name: string;
          last_name: string;
          phone: string;
          email?: string | null;
          date_of_birth: string;
          national_id_encrypted: string;
          profile_photo_url?: string | null;
          vehicle_type: 'motorcycle' | 'bicycle' | 'car' | 'scooter';
          vehicle_plate?: string | null;
          vehicle_model?: string | null;
          vehicle_year?: number | null;
          driver_license_number?: string | null;
          driver_license_expiry?: string | null;
          insurance_policy_number?: string | null;
          insurance_expiry?: string | null;
          primary_zone_id?: string | null;
          secondary_zones?: string[];
          max_delivery_radius_km?: number;
          status?: 'online' | 'busy' | 'offline' | 'suspended';
          current_location?: unknown | null;
          location_updated_at?: string | null;
          current_delivery_id?: string | null;
          max_concurrent_orders?: number;
          current_order_count?: number;
          total_deliveries?: number;
          successful_deliveries?: number;
          average_rating?: number;
          total_ratings?: number;
          on_time_rate?: number;
          acceptance_rate?: number;
          earnings_balance?: number;
          total_earnings?: number;
          last_payout_at?: string | null;
          background_check_status?: 'pending' | 'passed' | 'failed';
          is_verified?: boolean;
          verified_at?: string | null;
          is_active?: boolean;
          suspended_reason?: string | null;
          suspended_until?: string | null;
          created_at?: string;
          updated_at?: string;
          last_active_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          first_name?: string;
          last_name?: string;
          phone?: string;
          email?: string | null;
          date_of_birth?: string;
          national_id_encrypted?: string;
          profile_photo_url?: string | null;
          vehicle_type?: 'motorcycle' | 'bicycle' | 'car' | 'scooter';
          vehicle_plate?: string | null;
          vehicle_model?: string | null;
          vehicle_year?: number | null;
          driver_license_number?: string | null;
          driver_license_expiry?: string | null;
          insurance_policy_number?: string | null;
          insurance_expiry?: string | null;
          primary_zone_id?: string | null;
          secondary_zones?: string[];
          max_delivery_radius_km?: number;
          status?: 'online' | 'busy' | 'offline' | 'suspended';
          current_location?: unknown | null;
          location_updated_at?: string | null;
          current_delivery_id?: string | null;
          max_concurrent_orders?: number;
          current_order_count?: number;
          total_deliveries?: number;
          successful_deliveries?: number;
          average_rating?: number;
          total_ratings?: number;
          on_time_rate?: number;
          acceptance_rate?: number;
          earnings_balance?: number;
          total_earnings?: number;
          last_payout_at?: string | null;
          background_check_status?: 'pending' | 'passed' | 'failed';
          is_verified?: boolean;
          verified_at?: string | null;
          is_active?: boolean;
          suspended_reason?: string | null;
          suspended_until?: string | null;
          created_at?: string;
          updated_at?: string;
          last_active_at?: string | null;
        };
        Relationships: [];
      };
      prescriptions: {
        Row: {
          id: string;
          patient_id: string;
          pharmacy_id: string | null;
          prescription_number: string;
          external_reference: string | null;
          image_url: string;
          image_urls: string[];
          thumbnail_url: string | null;
          status: 'pending' | 'ai_processing' | 'ai_verified' | 'needs_pharmacist' | 'pharmacist_verified' | 'rejected' | 'preparing' | 'ready' | 'awaiting_courier' | 'delivering' | 'delivered' | 'cancelled';
          doctor_name: string | null;
          doctor_license: string | null;
          clinic_name: string | null;
          clinic_address: string | null;
          prescription_date: string | null;
          expiry_date: string | null;
          is_chronic: boolean;
          refill_allowed: boolean;
          refills_remaining: number;
          medications: Json;
          subtotal: number | null;
          insurance_coverage: number;
          delivery_fee: number | null;
          discount_amount: number;
          total_amount: number | null;
          delivery_address_id: string | null;
          delivery_instructions: string | null;
          requested_delivery_time: string | null;
          estimated_delivery_time: string | null;
          assigned_pharmacist_id: string | null;
          assigned_courier_id: string | null;
          ai_verification_id: string | null;
          pharmacist_verified_at: string | null;
          pharmacist_notes: string | null;
          has_controlled_substance: boolean;
          has_interaction_warning: boolean;
          requires_id_check: boolean;
          requires_signature: boolean;
          priority_score: number;
          priority_tier: 'critical' | 'high' | 'normal' | 'low';
          delivered_at: string | null;
          delivery_proof: Json | null;
          delivery_signature_url: string | null;
          delivery_otp: string | null;
          delivery_otp_verified: boolean;
          patient_rating: number | null;
          patient_feedback: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          patient_id: string;
          pharmacy_id?: string | null;
          prescription_number?: string;
          external_reference?: string | null;
          image_url: string;
          image_urls?: string[];
          thumbnail_url?: string | null;
          status?: 'pending' | 'ai_processing' | 'ai_verified' | 'needs_pharmacist' | 'pharmacist_verified' | 'rejected' | 'preparing' | 'ready' | 'awaiting_courier' | 'delivering' | 'delivered' | 'cancelled';
          doctor_name?: string | null;
          doctor_license?: string | null;
          clinic_name?: string | null;
          clinic_address?: string | null;
          prescription_date?: string | null;
          expiry_date?: string | null;
          is_chronic?: boolean;
          refill_allowed?: boolean;
          refills_remaining?: number;
          medications?: Json;
          subtotal?: number | null;
          insurance_coverage?: number;
          delivery_fee?: number | null;
          discount_amount?: number;
          total_amount?: number | null;
          delivery_address_id?: string | null;
          delivery_instructions?: string | null;
          requested_delivery_time?: string | null;
          estimated_delivery_time?: string | null;
          assigned_pharmacist_id?: string | null;
          assigned_courier_id?: string | null;
          ai_verification_id?: string | null;
          pharmacist_verified_at?: string | null;
          pharmacist_notes?: string | null;
          has_controlled_substance?: boolean;
          has_interaction_warning?: boolean;
          requires_id_check?: boolean;
          requires_signature?: boolean;
          priority_score?: number;
          priority_tier?: 'critical' | 'high' | 'normal' | 'low';
          delivered_at?: string | null;
          delivery_proof?: Json | null;
          delivery_signature_url?: string | null;
          delivery_otp?: string | null;
          delivery_otp_verified?: boolean;
          patient_rating?: number | null;
          patient_feedback?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          patient_id?: string;
          pharmacy_id?: string | null;
          prescription_number?: string;
          external_reference?: string | null;
          image_url?: string;
          image_urls?: string[];
          thumbnail_url?: string | null;
          status?: 'pending' | 'ai_processing' | 'ai_verified' | 'needs_pharmacist' | 'pharmacist_verified' | 'rejected' | 'preparing' | 'ready' | 'awaiting_courier' | 'delivering' | 'delivered' | 'cancelled';
          doctor_name?: string | null;
          doctor_license?: string | null;
          clinic_name?: string | null;
          clinic_address?: string | null;
          prescription_date?: string | null;
          expiry_date?: string | null;
          is_chronic?: boolean;
          refill_allowed?: boolean;
          refills_remaining?: number;
          medications?: Json;
          subtotal?: number | null;
          insurance_coverage?: number;
          delivery_fee?: number | null;
          discount_amount?: number;
          total_amount?: number | null;
          delivery_address_id?: string | null;
          delivery_instructions?: string | null;
          requested_delivery_time?: string | null;
          estimated_delivery_time?: string | null;
          assigned_pharmacist_id?: string | null;
          assigned_courier_id?: string | null;
          ai_verification_id?: string | null;
          pharmacist_verified_at?: string | null;
          pharmacist_notes?: string | null;
          has_controlled_substance?: boolean;
          has_interaction_warning?: boolean;
          requires_id_check?: boolean;
          requires_signature?: boolean;
          priority_score?: number;
          priority_tier?: 'critical' | 'high' | 'normal' | 'low';
          delivered_at?: string | null;
          delivery_proof?: Json | null;
          delivery_signature_url?: string | null;
          delivery_otp?: string | null;
          delivery_otp_verified?: boolean;
          patient_rating?: number | null;
          patient_feedback?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'prescriptions_patient_id_fkey';
            columns: ['patient_id'];
            referencedRelation: 'patients';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'prescriptions_pharmacy_id_fkey';
            columns: ['pharmacy_id'];
            referencedRelation: 'pharmacies';
            referencedColumns: ['id'];
          }
        ];
      };
      prescription_events: {
        Row: {
          id: string;
          prescription_id: string;
          event_type: string;
          event_data: Json;
          actor_id: string | null;
          actor_type: 'patient' | 'pharmacist' | 'courier' | 'system' | 'admin' | null;
          actor_name: string | null;
          previous_event_id: string | null;
          event_hash: string | null;
          ip_address: string | null;
          user_agent: string | null;
          device_info: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          prescription_id: string;
          event_type: string;
          event_data?: Json;
          actor_id?: string | null;
          actor_type?: 'patient' | 'pharmacist' | 'courier' | 'system' | 'admin' | null;
          actor_name?: string | null;
          previous_event_id?: string | null;
          event_hash?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          device_info?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          prescription_id?: string;
          event_type?: string;
          event_data?: Json;
          actor_id?: string | null;
          actor_type?: 'patient' | 'pharmacist' | 'courier' | 'system' | 'admin' | null;
          actor_name?: string | null;
          previous_event_id?: string | null;
          event_hash?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          device_info?: Json | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'prescription_events_prescription_id_fkey';
            columns: ['prescription_id'];
            referencedRelation: 'prescriptions';
            referencedColumns: ['id'];
          }
        ];
      };
      ai_verification_results: {
        Row: {
          id: string;
          prescription_id: string;
          ocr_confidence: number | null;
          extracted_text: string | null;
          raw_ocr_response: Json | null;
          entities: Json;
          drug_matches: Json;
          dosage_validation: Json;
          interactions: Json;
          controlled_substances: Json;
          fraud_indicators: Json;
          fraud_score: number;
          verification_status: 'approved' | 'needs_review' | 'rejected' | 'processing' | 'failed';
          confidence_score: number | null;
          attention_required: boolean;
          attention_reasons: string[];
          model_version: string | null;
          processing_time_ms: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          prescription_id: string;
          ocr_confidence?: number | null;
          extracted_text?: string | null;
          raw_ocr_response?: Json | null;
          entities?: Json;
          drug_matches?: Json;
          dosage_validation?: Json;
          interactions?: Json;
          controlled_substances?: Json;
          fraud_indicators?: Json;
          fraud_score?: number;
          verification_status: 'approved' | 'needs_review' | 'rejected' | 'processing' | 'failed';
          confidence_score?: number | null;
          attention_required?: boolean;
          attention_reasons?: string[];
          model_version?: string | null;
          processing_time_ms?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          prescription_id?: string;
          ocr_confidence?: number | null;
          extracted_text?: string | null;
          raw_ocr_response?: Json | null;
          entities?: Json;
          drug_matches?: Json;
          dosage_validation?: Json;
          interactions?: Json;
          controlled_substances?: Json;
          fraud_indicators?: Json;
          fraud_score?: number;
          verification_status?: 'approved' | 'needs_review' | 'rejected' | 'processing' | 'failed';
          confidence_score?: number | null;
          attention_required?: boolean;
          attention_reasons?: string[];
          model_version?: string | null;
          processing_time_ms?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'ai_verification_results_prescription_id_fkey';
            columns: ['prescription_id'];
            referencedRelation: 'prescriptions';
            referencedColumns: ['id'];
          }
        ];
      };
      morocco_drug_database: {
        Row: {
          id: string;
          dci_code: string | null;
          morocco_amm_code: string | null;
          brand_name: string;
          generic_name: string;
          manufacturer: string | null;
          therapeutic_class: string | null;
          atc_code: string | null;
          schedule: 'OTC' | 'Rx' | 'Controlled_III' | 'Controlled_IV' | 'Narcotic' | null;
          available_forms: Json;
          standard_dosages: Json;
          contraindications: Json;
          drug_interactions: Json;
          ppv: number | null;
          pfht: number | null;
          reimbursement_rate: number | null;
          last_updated: string;
          is_active: boolean;
        };
        Insert: {
          id?: string;
          dci_code?: string | null;
          morocco_amm_code?: string | null;
          brand_name: string;
          generic_name: string;
          manufacturer?: string | null;
          therapeutic_class?: string | null;
          atc_code?: string | null;
          schedule?: 'OTC' | 'Rx' | 'Controlled_III' | 'Controlled_IV' | 'Narcotic' | null;
          available_forms?: Json;
          standard_dosages?: Json;
          contraindications?: Json;
          drug_interactions?: Json;
          ppv?: number | null;
          pfht?: number | null;
          reimbursement_rate?: number | null;
          last_updated?: string;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          dci_code?: string | null;
          morocco_amm_code?: string | null;
          brand_name?: string;
          generic_name?: string;
          manufacturer?: string | null;
          therapeutic_class?: string | null;
          atc_code?: string | null;
          schedule?: 'OTC' | 'Rx' | 'Controlled_III' | 'Controlled_IV' | 'Narcotic' | null;
          available_forms?: Json;
          standard_dosages?: Json;
          contraindications?: Json;
          drug_interactions?: Json;
          ppv?: number | null;
          pfht?: number | null;
          reimbursement_rate?: number | null;
          last_updated?: string;
          is_active?: boolean;
        };
        Relationships: [];
      };
      insurance_providers: {
        Row: {
          id: string;
          code: string;
          name: string;
          name_ar: string | null;
          name_fr: string | null;
          type: 'public' | 'private' | 'mutual';
          default_coverage_rate: number;
          coverage_rules: Json;
          api_available: boolean;
          api_endpoint: string | null;
          claim_method: 'api' | 'email' | 'manual' | 'portal';
          claims_email: string | null;
          claims_phone: string | null;
          portal_url: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          name: string;
          name_ar?: string | null;
          name_fr?: string | null;
          type: 'public' | 'private' | 'mutual';
          default_coverage_rate?: number;
          coverage_rules?: Json;
          api_available?: boolean;
          api_endpoint?: string | null;
          claim_method?: 'api' | 'email' | 'manual' | 'portal';
          claims_email?: string | null;
          claims_phone?: string | null;
          portal_url?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          name?: string;
          name_ar?: string | null;
          name_fr?: string | null;
          type?: 'public' | 'private' | 'mutual';
          default_coverage_rate?: number;
          coverage_rules?: Json;
          api_available?: boolean;
          api_endpoint?: string | null;
          claim_method?: 'api' | 'email' | 'manual' | 'portal';
          claims_email?: string | null;
          claims_phone?: string | null;
          portal_url?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      patient_health_graphs: {
        Row: {
          patient_id: string;
          chronic_conditions: Json;
          active_medications: Json;
          historical_medications: Json;
          known_interactions: Json;
          allergies: Json;
          adherence_metrics: Json;
          refill_patterns: Json;
          insurance_utilization: Json;
          ltv_score: number | null;
          predicted_monthly_value: number | null;
          churn_risk_score: number | null;
          next_likely_refill_date: string | null;
          prescription_count: number;
          first_prescription_at: string | null;
          last_prescription_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          patient_id: string;
          chronic_conditions?: Json;
          active_medications?: Json;
          historical_medications?: Json;
          known_interactions?: Json;
          allergies?: Json;
          adherence_metrics?: Json;
          refill_patterns?: Json;
          insurance_utilization?: Json;
          ltv_score?: number | null;
          predicted_monthly_value?: number | null;
          churn_risk_score?: number | null;
          next_likely_refill_date?: string | null;
          prescription_count?: number;
          first_prescription_at?: string | null;
          last_prescription_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          patient_id?: string;
          chronic_conditions?: Json;
          active_medications?: Json;
          historical_medications?: Json;
          known_interactions?: Json;
          allergies?: Json;
          adherence_metrics?: Json;
          refill_patterns?: Json;
          insurance_utilization?: Json;
          ltv_score?: number | null;
          predicted_monthly_value?: number | null;
          churn_risk_score?: number | null;
          next_likely_refill_date?: string | null;
          prescription_count?: number;
          first_prescription_at?: string | null;
          last_prescription_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'patient_health_graphs_patient_id_fkey';
            columns: ['patient_id'];
            referencedRelation: 'patients';
            referencedColumns: ['id'];
          }
        ];
      };
      pharmacy_intelligence: {
        Row: {
          pharmacy_id: string;
          avg_verification_time_seconds: number | null;
          avg_fulfillment_time_minutes: number | null;
          fulfillment_success_rate: number | null;
          rejection_rate: number | null;
          stockout_frequency: Json;
          demand_forecast: Json;
          popular_medications: Json;
          insurance_claim_success_rate: Json;
          current_queue_depth: number;
          avg_queue_wait_minutes: number | null;
          peak_hours: Json;
          patient_satisfaction_score: number | null;
          pharmacist_accuracy_score: number | null;
          performance_score: number | null;
          updated_at: string;
        };
        Insert: {
          pharmacy_id: string;
          avg_verification_time_seconds?: number | null;
          avg_fulfillment_time_minutes?: number | null;
          fulfillment_success_rate?: number | null;
          rejection_rate?: number | null;
          stockout_frequency?: Json;
          demand_forecast?: Json;
          popular_medications?: Json;
          insurance_claim_success_rate?: Json;
          current_queue_depth?: number;
          avg_queue_wait_minutes?: number | null;
          peak_hours?: Json;
          patient_satisfaction_score?: number | null;
          pharmacist_accuracy_score?: number | null;
          performance_score?: number | null;
          updated_at?: string;
        };
        Update: {
          pharmacy_id?: string;
          avg_verification_time_seconds?: number | null;
          avg_fulfillment_time_minutes?: number | null;
          fulfillment_success_rate?: number | null;
          rejection_rate?: number | null;
          stockout_frequency?: Json;
          demand_forecast?: Json;
          popular_medications?: Json;
          insurance_claim_success_rate?: Json;
          current_queue_depth?: number;
          avg_queue_wait_minutes?: number | null;
          peak_hours?: Json;
          patient_satisfaction_score?: number | null;
          pharmacist_accuracy_score?: number | null;
          performance_score?: number | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'pharmacy_intelligence_pharmacy_id_fkey';
            columns: ['pharmacy_id'];
            referencedRelation: 'pharmacies';
            referencedColumns: ['id'];
          }
        ];
      };
      payments: {
        Row: {
          id: string;
          prescription_id: string | null;
          patient_id: string;
          amount: number;
          currency: string;
          payment_method: 'card' | 'cod' | 'mobile_money' | 'bank_transfer' | 'insurance_only';
          provider: string;
          status: 'pending' | 'processing' | 'authorized' | 'captured' | 'failed' | 'refunded' | 'partially_refunded' | 'disputed' | 'cancelled';
          provider_transaction_id: string | null;
          provider_response: Json;
          card_last_four: string | null;
          card_brand: string | null;
          subtotal: number;
          insurance_coverage: number;
          delivery_fee: number;
          discount_amount: number;
          cod_collected_at: string | null;
          cod_collected_by: string | null;
          refund_amount: number | null;
          refund_reason: string | null;
          refunded_at: string | null;
          created_at: string;
          captured_at: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          prescription_id?: string | null;
          patient_id: string;
          amount: number;
          currency?: string;
          payment_method: 'card' | 'cod' | 'mobile_money' | 'bank_transfer' | 'insurance_only';
          provider: string;
          status?: 'pending' | 'processing' | 'authorized' | 'captured' | 'failed' | 'refunded' | 'partially_refunded' | 'disputed' | 'cancelled';
          provider_transaction_id?: string | null;
          provider_response?: Json;
          card_last_four?: string | null;
          card_brand?: string | null;
          subtotal: number;
          insurance_coverage?: number;
          delivery_fee?: number;
          discount_amount?: number;
          cod_collected_at?: string | null;
          cod_collected_by?: string | null;
          refund_amount?: number | null;
          refund_reason?: string | null;
          refunded_at?: string | null;
          created_at?: string;
          captured_at?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          prescription_id?: string | null;
          patient_id?: string;
          amount?: number;
          currency?: string;
          payment_method?: 'card' | 'cod' | 'mobile_money' | 'bank_transfer' | 'insurance_only';
          provider?: string;
          status?: 'pending' | 'processing' | 'authorized' | 'captured' | 'failed' | 'refunded' | 'partially_refunded' | 'disputed' | 'cancelled';
          provider_transaction_id?: string | null;
          provider_response?: Json;
          card_last_four?: string | null;
          card_brand?: string | null;
          subtotal?: number;
          insurance_coverage?: number;
          delivery_fee?: number;
          discount_amount?: number;
          cod_collected_at?: string | null;
          cod_collected_by?: string | null;
          refund_amount?: number | null;
          refund_reason?: string | null;
          refunded_at?: string | null;
          created_at?: string;
          captured_at?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'payments_patient_id_fkey';
            columns: ['patient_id'];
            referencedRelation: 'patients';
            referencedColumns: ['id'];
          }
        ];
      };
      notifications: {
        Row: {
          id: string;
          recipient_id: string;
          recipient_type: 'patient' | 'pharmacist' | 'courier' | 'admin';
          channel: 'sms' | 'push' | 'email' | 'whatsapp';
          template_code: string;
          title: string | null;
          body: string;
          data: Json;
          prescription_id: string | null;
          status: 'pending' | 'queued' | 'sent' | 'delivered' | 'failed' | 'read';
          provider: string | null;
          provider_message_id: string | null;
          sent_at: string | null;
          delivered_at: string | null;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          recipient_id: string;
          recipient_type: 'patient' | 'pharmacist' | 'courier' | 'admin';
          channel: 'sms' | 'push' | 'email' | 'whatsapp';
          template_code: string;
          title?: string | null;
          body: string;
          data?: Json;
          prescription_id?: string | null;
          status?: 'pending' | 'queued' | 'sent' | 'delivered' | 'failed' | 'read';
          provider?: string | null;
          provider_message_id?: string | null;
          sent_at?: string | null;
          delivered_at?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          recipient_id?: string;
          recipient_type?: 'patient' | 'pharmacist' | 'courier' | 'admin';
          channel?: 'sms' | 'push' | 'email' | 'whatsapp';
          template_code?: string;
          title?: string | null;
          body?: string;
          data?: Json;
          prescription_id?: string | null;
          status?: 'pending' | 'queued' | 'sent' | 'delivered' | 'failed' | 'read';
          provider?: string | null;
          provider_message_id?: string | null;
          sent_at?: string | null;
          delivered_at?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
    CompositeTypes: {};
  };
}

// Helper types for common use cases
export type Patient = Database['public']['Tables']['patients']['Row'];
export type PatientInsert = Database['public']['Tables']['patients']['Insert'];
export type PatientUpdate = Database['public']['Tables']['patients']['Update'];

export type Pharmacy = Database['public']['Tables']['pharmacies']['Row'];
export type PharmacyInsert = Database['public']['Tables']['pharmacies']['Insert'];

export type PharmacyStaff = Database['public']['Tables']['pharmacy_staff']['Row'];
export type Courier = Database['public']['Tables']['couriers']['Row'];

export type Prescription = Database['public']['Tables']['prescriptions']['Row'];
export type PrescriptionInsert = Database['public']['Tables']['prescriptions']['Insert'];
export type PrescriptionUpdate = Database['public']['Tables']['prescriptions']['Update'];

export type PrescriptionEvent = Database['public']['Tables']['prescription_events']['Row'];
export type AIVerificationResult = Database['public']['Tables']['ai_verification_results']['Row'];

export type MoroccoDrug = Database['public']['Tables']['morocco_drug_database']['Row'];
export type InsuranceProvider = Database['public']['Tables']['insurance_providers']['Row'];

export type PatientHealthGraph = Database['public']['Tables']['patient_health_graphs']['Row'];
export type PharmacyIntelligence = Database['public']['Tables']['pharmacy_intelligence']['Row'];

export type Payment = Database['public']['Tables']['payments']['Row'];
export type Notification = Database['public']['Tables']['notifications']['Row'];

// Status enums for convenience
export type PrescriptionStatus = Prescription['status'];
export type PaymentStatus = Payment['status'];
export type CourierStatus = Courier['status'];
export type PharmacyTier = Pharmacy['tier'];

// Supabase helper types (compatible with generated types)
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];

export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];

export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];
